kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: kubernetes
    resources:
    #soft limit
      requests:
        cpu: "64m"
        memory: "250mi"
    #hard limit
      limits:
        cpu: "256m"
        memory: "750mi"