apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0708750f9ca670723

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: pv-testing
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pv
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: ebs-claim


---

kind: Service
apiVersion: v1
metadata:
  name: nginx
  #namespace: expense
  labels:
    component: nginx-service
spec:
  type: LoadBalancer
  selector:
    purpose: pv-testing
  ports:
  - port: 80
    nodePort: 31134
    targetPort: 80
      
